version: "3.8"

services:
  api:
    build: .././ecommerce-api
    container_name: ecommerce-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["node", "src/index.js"]

  db:
    image: postgres:15
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ../frontend
    container_name: ecommerce-frontend
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  db_data:
